### PR TITLE
RT110379: Added Lance's AES support

### PR DESCRIPTION
**Pull request by choroba**
I resolved all the conflicts. Please verify the changes.

### CODE REVIEW

**Comment by choroba** [comment]
This also seems to fix [RT99284](https://rt.cpan.org/Ticket/Display.html?id=99284).

**Comment by renormalist** [comment]
Thank you very much. This is very much how I preferred it but didn't found the time to do it. I should get some spare cycles to do a cpan release from that.

**Comment by lkinley** [comment]
I've done quite a bit more work since the 1.42 rebase.  I'm also very close to eliminating the need for Math::Pari.

**Comment by choroba** [comment]
Sounds great. Maybe you can rebase your repo onto the merge commit here then to make future merges easier?

**Pull request merged**
